image: microsoft/dotnet:latest

stages:
  - build
  - test

before_script:
  - "dotnet restore"

build:
  stage: build
  variables:
    build_path: "src"
  script:
    - "cd $build_path"
    - "dotnet build"

test:
  stage: test
  variables:
    test_path: "src"
  script:
    - "cd $test_path"
    - "dotnet test"