image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - "build"
  - "test"

variables:
  test: "Example.Test"

before_script:
  - "cd src"
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"


test:
  stage: test
  script:
    - "cd src/Otus.Teaching.PromoCodeFactory.Homework.UnitTests"
    - "dotnet test"
  
