image: mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - build
  - test

build:
  tags: 
    - docker
  stage: build
  script:
    - dotnet build src/Otus.Teaching.PromoCodeFactory.WebHost/Otus.Teaching.PromoCodeFactory.WebHost.csproj -c Release -o content
  artifacts:
    paths:
      - content

tests:
  tags:
    - docker
  stage: test
  script:
    - cd ./src
    - dotnet test
