image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test

before_script:
    - cd src
    - dotnet restore

build:
  stage: build
  script:
    - 'cd ./src'
    - 'dotnet build'
test:
    stage: test
    script:
    - 'cd ./src'
    - 'dotnet test'
