image: mcr.microsoft.com/dotnet/sdk:3.1.422-alpine3.16

stages:
  - build
  - test

variables:
  SLN_PATH: src/Otus.Teaching.PromoCodeFactory.sln

build:
  stage: build
  script:
    - 'dotnet build  $SLN_PATH'

tests:
  stage: test
  script:
    - 'dotnet test  SLN_PATH'
