image: docker:stable

services:
  - docker:dind
  
stages:
    - build
    - test

before_script:
  - docker info

build:
  only:
    - master
  before_script:
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest src
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  after_script:
    - docker logout ${CI_REGISTRY}
  stage: build
  tags: 
    - docker
    
unit_tests:
    stage: test
    script: dotnet vstest *UnitTests/bin/*/*/*UnitTests.dll --Blame
    rules:
        - exists:
            - "*UnitTests/Otus.Teaching.PromoCodeFactory.UnitTests.csproj"